FMS.Web/Controllers/VehicleFuelManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using FMS.Service;
using FMS.Web.ViewModels;
using FMS.Model;
using Kendo.Mvc.UI;
using AutoMapper;
using Kendo.Mvc.Extensions;
using System.Web;
using System.IO;
using FMS.Web.CustomActionFilters;
using FMS.Common;
using FMS.Web.Identity;
using Microsoft.AspNet.Identity;


namespace FMS.Web.Controllers
{
    


    [Authorize]
    [NoDirectAccess]
    public class VehicleFuelManagementController : BaseController
    {
        #region 1. Private Members

        private readonly IVehicleManagementService _vehicleManagementService;
        private readonly ICenterService _centerService;       
        private readonly ISystemParameterService _systemParameterService;
        private readonly IContactDetailService _contactDetailService;
        private readonly IVehicleServiceService _vehicleServiceService;
        private readonly IVehicleFuelManagementService _vehicleFuelManagementService;
        private readonly IDepotTankService _depotTankService;


        #endregion

        #region 2. Constructors
        public VehicleFuelManagementController(IVehicleManagementService vehicleManagementService
            , IVehicleFuelManagementService vehicleFuelManagementService
            ,IDepotTankService depotTankService
            , ICenterService centerService           
            , IContactDetailService contactDetailService
            , IVehicleServiceService vehicleServiceService
            , IAuditingService auditingService
            , UserManager<IdentityUser, Guid> userManager           
            , IBusinessUnitService businessUnitService
            , IBusinessGroupService businessGroupService
            , IModelService modelService
            , IAppRoleInterfaceAccessService appRoleInterfaceAccessService
            , IAppRoleMenuAccessService appRoleMenuAccessService
            , IAppRoleActionAccessService appRoleActionAccessService
            , IAppIssueService appIssueService
            , ISystemParameterService systemParameterService
            , ISystemParameterCodeService systemParameterCodeService

        ) : base(auditingService, userManager, contactDetailService, vehicleManagementService, vehicleServiceService
           , businessUnitService
           , businessGroupService
           , centerService
           , modelService
           , depotTankService
           , appRoleInterfaceAccessService
           , appRoleMenuAccessService
           , appRoleActionAccessService
            , systemParameterCodeService
            , systemParameterService
            , appIssueService
           )
        {
            _vehicleManagementService = vehicleManagementService;
            _centerService = centerService;
            _systemParameterService = systemParameterService;
            _contactDetailService = contactDetailService;
            _vehicleServiceService = vehicleServiceService;
            _vehicleFuelManagementService = vehicleFuelManagementService;
            _depotTankService = depotTankService;
        }
        #endregion

        #region 3. Actions

        #region 3.a. Get View Related Actions

        [HttpGet]
        [UserInterfaceAuthorization(Parameters.Interface.FUEL_REGISTER)]
        public ActionResult VehicleRefuels(string message, bool isError)
        {
            ViewBag.NotificationMessage = message;
            ViewBag.NotificationIsError = isError;

            PopulateSelectListDataSources();

            return View();
        }


        [HttpGet]
        [UserActionAuthorization(Parameters.Action.VIEW_VEHICLE_FUEL_REGISTER)]
        public ActionResult ViewVehicleRefuelDetails(int id)
        {
            var v = _vehicleFuelManagementService.GetVehicleRefuelById(id);

            var vm = Mapper.Map<VehicleRefuel, VehicleRefuelDisplayViewModel>(v);

            return View("VehicleRefuelDetailsView", vm);      
        }


        [HttpGet]
        [UserActionAuthorization(Parameters.Action.MANAGE_VEHICLE_FUEL_REGISTER)]
        public ActionResult EditVehicleRefuelDetails(int vehicleRefuelId)
        {
            var vs = _vehicleFuelManagementService.GetVehicleRefuelById(vehicleRefuelId);

            var vm = Mapper.Map<VehicleRefuel, VehicleRefuelEditViewModel>(vs);

            PopulateSelectListDataSources();

            return View("VehicleRefuelEditDetailsForm", vm);
        }

        [HttpGet]
        [UserActionAuthorization(Parameters.Action.MANAGE_VEHICLE_FUEL_REGISTER)]
        public ActionResult GetCreateVehicleRefuelMasterDetails()
        {
            var vm = new VehicleRefuelEditViewModel { Id = 0, Date = DateTime.Today };

            PopulateSelectListDataSources();

            return View("VehicleRefuelCreateMasterForm", vm);
        }

        [HttpGet]
        [UserActionAuthorization(Parameters.Action.ACQUIT_FUEL_VOUCHER)]
        public ActionResult GetVehicleRefuelDetails(int vehicleRefuelId)
        {

            var r = _vehicleFuelManagementService.GetVehicleRefuelById(vehicleRefuelId);

            var vm = Mapper.Map<VehicleRefuel, VehicleRefuelEditViewModel>(r);

            return PartialView("VehicleRefuelAcquitalForm", vm);
        }


        #endregion

        #region 3.b. Get List of Values Related Actions


        #endregion

        #region 3.c. Grid Related Actions

        public ActionResult GetVehicleRefuelsList([DataSourceRequest] DataSourceRequest request
            ,string fuelVoucherNumber, string tankNumber, int center, int fuelType, bool showVouchersNotAcquitted)
        {

            var vs = _vehicleFuelManagementService.GetFilterByCenterPermission(CurrentUser, tankNumber, fuelVoucherNumber, fuelType,center, showVouchersNotAcquitted);

            var vm = Mapper.Map<IEnumerable<VehicleRefuel>, IEnumerable<VehicleRefuelDisplayViewModel>>(vs);

            return Json(vm.ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [UserActionAuthorization(Parameters.Action.MANAGE_VEHICLE_FUEL_REGISTER)]
        public ActionResult CreateVehicleRefuel([DataSourceRequest] DataSourceRequest request, VehicleRefuelEditViewModel entityViewModel)
        {

            try
            {
                if (entityViewModel != null)
                {
                    ModelState.Remove("VoucherReceiptNumber");

                    if (entityViewModel.IsBowserFuel == true)
                    {
                        ModelState.Remove("FuelDistributorId");
                    }
                    else
                    {
                        ModelState.Remove("BowserNumber");
                    }

                    if (entityViewModel.VehicleId > 0 || entityViewModel.VehicleId != null) {
                        var v = _vehicleManagementService.GetVehicleById((int)entityViewModel.VehicleId);
                        entityViewModel.RegistrationNumber = v.RegistrationNumber;
                    }                    

                    if (ModelState.IsValid)
                    {
                        var r = Mapper.Map<VehicleRefuelEditViewModel, VehicleRefuel>(entityViewModel);


                        r.CreatedBy = CurrentUser;
                        r.CreatedDate = DateTime.Now;

                        _vehicleFuelManagementService.Create(r);
                        _vehicleFuelManagementService.Save();
                        CreateAuditTrail(Parameters.DatabaseAction.Insert, Parameters.SubSystem.Center, Parameters.Table.Center);
                        entityViewModel.Id = r.Id;

                        //update vehicle Current Mileage when refuelling
                        UpdateVehicleCurrentMileage(r);

                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }


            return Json(new[]{entityViewModel}.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [UserActionAuthorization(Parameters.Action.MANAGE_VEHICLE_FUEL_REGISTER)]
        public ActionResult EditVehicleRefuel([DataSourceRequest] DataSourceRequest request, VehicleRefuelEditViewModel entityViewModel)
        {
            try
            {

                if (entityViewModel != null)
                {
                    ModelState.Remove("VoucherReceiptNumber");                   

                    if (entityViewModel.IsBowserFuel == true)
                    {
                        ModelState.Remove("FuelDistributorId");
                    }
                    else
                    {
                        ModelState.Remove("BowserNumber");
                    }

                    if (entityViewModel.VehicleId > 0 || entityViewModel.VehicleId != null)
                    {
                        var v = _vehicleManagementService.GetVehicleById((int)entityViewModel.VehicleId);
                        entityViewModel.RegistrationNumber = v.RegistrationNumber;
                    }

                    if (ModelState.IsValid)
                    {
                        var r = Mapper.Map<VehicleRefuelEditViewModel, VehicleRefuel>(entityViewModel);

                        r.LastUpdatedBy = CurrentUser;
                        r.LastUpdatedDate = DateTime.Now;

                        _vehicleFuelManagementService.Update(r);
                        _vehicleFuelManagementService.Save();

                        CreateAuditTrail(Parameters.DatabaseAction.Update, Parameters.SubSystem.VehicleRefuel, Parameters.Table.VehicleRefuel);

                        //update vehicle Current Mileage when refuelling
                        UpdateVehicleCurrentMileage(r);

                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

FMS.Web/Views/VehicleFuelManagement/VehicleRefuelAcquitalForm.cshtml
@using FMS.Web.ViewModels
@using FMS.Web.CustomHTMLHelpers

@model VehicleRefuelEditViewModel


@using (Html.BeginForm("frmVehicleRefuelAcquital"))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="container-fluid" id="FormContainer">
        <div class="row no-gutters h-100 justify-content-center align-items-center">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table no-border">
                        <tr>
                            <th style="vertical-align:middle">Fuel Voucher #</th>
                            <td>
                                @Html.HiddenFor(model => model.Id)
                            <h4>@Html.DisplayFor(m => m.VoucherNumber)</h4>
                        </td>
                    </tr>
                    <tr>
                        <th>&nbsp;</th>
                        <td>
                            @(Html.Kendo().CheckBoxFor(model => model.IsVoucherAcquitted))
                            <br />@Html.ValidationMessageFor(model => model.IsVoucherAcquitted)
                        </td>
                    </tr>
                    <tr>
                        <th>@Html.LabelFor(model => model.VoucherReceiptNumber)</th>
                        <td>
                            @(Html.Kendo().TextBoxFor(model => model.VoucherReceiptNumber).HtmlAttributes(new { style = "width:250px;background-color:#e6e6e6;" }))                      
                    </td>
                </tr>


            </table>
        </div>
        </div>
        <div id="wndProgressIndicator"></div>
        </div>
        <div class="row h-100 justify-content-center align-items-center formButtonRow">
            @Html.Partial("_ModalFormButtons")
        </div>
        
    </div>
}

FMS.Web/Views/VehicleFuelManagement/VehicleRefuelCreateMasterForm.cshtml
@using FMS.Web.CustomHTMLHelpers
@model FMS.Web.ViewModels.VehicleRefuelEditViewModel

@{
    ViewBag.Title = "Step 1: Create Vehicle Refuel Details - Select Center, Refuel Date and Tank/Fuel Distributor";
}

<div class="container-fluid" style="margin-top:15px">
    <div class="row no-gutters h-100 justify-content-center align-items-center" style="background-color: azure; margin-top: 15px; margin-bottom: 15px;  padding: 5px;padding-left: 15px;">
        <div class="col-md-12">
            <div class="formHeadingRegion">
                <h4>@ViewBag.Title</h4>
            </div>
        </div>
    </div>
    <div class="row no-gutters h-100 justify-content-center align-items-center">
        <div class="col-md-12">
            @using (Html.BeginForm("CreateVehicleRefuelMasterDetails", "VehicleFuelManagement", FormMethod.Post, new { id="frmCreateVehicleRefuelMasterDetails" }))
            {
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.AntiForgeryToken()
                <div class="container-fluid" id="FormContainer" style="margin-bottom:15px;">
                    <div class="row no-gutters h-100 justify-content-center align-items-center">
                        <div class="col-md-4">
                            <div class="table-responsive">
                                <table class="table no-border">
                                    <tr>
                                        <th> @Html.LabelForRequired(m => m.CenterId)</th>
                                        <td>
                                            @Html.HiddenFor(m => m.Id)
                                            @(Html.Kendo().DropDownListFor(m => m.CenterId)
                                                                                                        .Name("CenterId")
                                                                                                        .DataValueField("Value")
                                                                                                        .DataTextField("Text")
                                                                                                        .OptionLabel(new { Text = "Select ...", Value = "" })
                                                                                                        .Filter(FilterType.Contains)
                                                                                                        .ValuePrimitive(true)
                                                                                                        .HtmlAttributes(new { style = "width:170px" })
                                                                                                        .BindTo((System.Collections.IEnumerable)ViewBag.Centers)
                                                                                                        .Events(events => events.Change("onCenterChange"))
                                            )
                                            <br /><span class="k-invalid-msg" data-for="CenterId"></span>
                                        </td>
                                    </tr>


                                </table>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="table-responsive">
                                <table class="table no-border">
                                    <tr>
                                        <th>@Html.LabelForRequired(m => m.Date)</th>
                                        <td>
                                            @(Html.Kendo().DatePickerFor(m => m.Date)
                                                                                                                .Name("Date")
                                                                                                                .HtmlAttributes(new { style = "width:170px" })
                                            )
                                            <br /><span class="k-invalid-msg" data-for="Date"></span>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="table-responsive">
                                <table class="table no-border">
                                    <tr>
                                        <th>&nbsp;</th>
                                        <td>
                                            <div style="display:inline-block;font-family: 'Roboto'">
                                                @(Html.Kendo().CheckBoxFor(m => m.IsBowserFuel)
                                                                                                    .Name("IsBowserFuel")
                                                )
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="row no-gutters h-100 justify-content-center align-items-center">
                        <div class="col-md-12" style="margin-bottom: -10px;margin-top: -30px;">
                            <hr />
                        </div>
                    </div>
                    <div class="row no-gutters h-100 justify-content-center align-items-center">
                        <div class="col-md-4">
                            <div class="table-responsive">
                                <table class="table no-border">
                                    <tr>
                                        <th>@Html.LabelForRequired(m => m.FuelDistributorId)</th>
                                        <td>
                                            @(Html.Kendo().DropDownListFor(m => m.FuelDistributorId)
                                                                                            .Name("FuelDistributorId")
                                                                                            .DataValueField("Value")
                                                                                            .DataTextField("Text")
                                                                                            .OptionLabel(new { Text = "Select ...", Value = "" })
                                                                                            .Filter(FilterType.Contains)
                                                                                            .ValuePrimitive(true)
                                                                                            .HtmlAttributes(new { style = "width:170px" })
                                                                                            .BindTo((System.Collections.IEnumerable)ViewBag.FuelDistributors)
                                            )
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="table-responsive">
                                <table class="table no-border">
                                    <tr>
                                        <th>@Html.LabelForRequired(m => m.BowserNumber)</th>
                                        <td>
                                            @(Html.Kendo().DropDownListFor(m => m.BowserNumber)
                                                                                            .Name("BowserNumber")
                                                                                            .DataValueField("Value")
                                                                                            .DataTextField("Text")
                                                                                            .OptionLabel(new { Text = "Select ...", Value = "" })
                                                                                            .Filter(FilterType.Contains)
                                                                                            .ValuePrimitive(true)
                                                                                            .HtmlAttributes(new { style = "width:170px" })
                                                                                            .BindTo((System.Collections.IEnumerable)ViewBag.FuelTanks)
                                            )
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="table-responsive">
                                <table class="table no-border">
                                    <tr>
                                        <th>@Html.LabelForRequired(m => m.UnitCost)</th>
                                        <td>
                                            @Html.EditorFor(m => m.UnitCost)
                                            <br /><span class="k-invalid-msg" data-for="UnitCost"></span>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>


                    </div>
                    <div class="row no-gutters h-100 justify-content-center align-items-center">
                        <div class="col-md-12" style="margin-bottom: -10px;margin-top: -30px;">
                            <hr />
                        </div>
                    </div>
                    <div class="row no-gutters h-100 justify-content-center align-items-center" style="float: right;margin-right: 50px;">
                        <div class="col-md-12">
                            <div>
                                @(Html.Kendo().Button()
                                                                            .Name("btnBottomNext")
                                                                            .Icon("arrow-end-right")
                                                                            .Content("Next")
                                                                            .HtmlAttributes(new { type = "submit", @class = "k-button k-primary" })
                                )
                                @(Html.Kendo().Button()
                                                                            .Name("btnBottomCancel")
                                                                            .Content("back")
                                                                            .HtmlAttributes(new { type = "button", @class = "k-button" })
                                                                            .Icon("undo")
                                )
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>

    </div>
</div>
@section scripts{
    <script>


        $(document).ready(function () {

            if (typeof (Storage) !== "undefined" && sessionStorage.vr01selectedCenter) {                
                    $("#CenterId").data("kendoDropDownList").value(sessionStorage.vr01selectedCenter); //pass value from previous view                
            }

            $("#btnBottomCancel").click(function (event) {
                window.location.href = "/VehicleFuelManagement/VehicleRefuels?message=NA&isError=false";
            });



            $("#IsBowserFuel").change(function () {
                if (this.checked) {
                    $("#BowserNumber").data().kendoDropDownList.enable(true);
                    $("#FuelDistributorId").data().kendoDropDownList.enable(false);
                }
                else {
                    $("#BowserNumber").data().kendoDropDownList.enable(false);
                    $("#FuelDistributorId").data().kendoDropDownList.enable(true);
                }
            });

            if ($("#IsBowserFuel").prop("checked")) {
                $("#BowserNumber").data().kendoDropDownList.enable(true);
                $("#FuelDistributorId").data().kendoDropDownList.enable(false);
            }
            else {
                $("#BowserNumber").data().kendoDropDownList.enable(false);
                $("#FuelDistributorId").data().kendoDropDownList.enable(true);
            }
        });

        function onCenterChange(e) {
            if (typeof (Storage) !== "undefined") {
                    sessionStorage.vr01selectedCenter = e.sender.value();
            }    
        }

        $("#frmCreateVehicleRefuelMasterDetails").submit(function (event) {

            var validator = $(this).kendoValidator().data("kendoValidator");

            if (!validator.validate()) {
                event.preventDefault();
            }  


        });


    </script>
    }