FMS.Web/Controllers/VehicleIncidentManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using FMS.Service;
using FMS.Web.ViewModels;
using FMS.Model;
using Kendo.Mvc.UI;
using AutoMapper;
using Kendo.Mvc.Extensions;
using System.Web;
using System.IO;
using FMS.Web.CustomActionFilters;
using FMS.Common;
using Microsoft.AspNet.Identity;
using FMS.Web.Identity;

namespace FMS.Web.Controllers
{
    [Authorize]
    [NoDirectAccess]
    public class VehicleIncidentManagementController : BaseController
    {
        #region 1. Private Members

        private readonly IVehicleManagementService _vehicleManagementService;
        private readonly IBusinessUnitService _businessUnitService;
        private readonly IBusinessGroupService _businessGroupService;
        private readonly ICenterService _centerService;
        private readonly IVehicleDisposalService _vehicleDisposalService;
        private readonly ISystemParameterService _systemParameterService;
        private readonly IContactDetailService _contactDetailService;
        private readonly IRegionService _regionService;
        private readonly IModelService _modelService;
        private readonly IVehicleTypeService _vehicleTypeService;
        private readonly IIncidentService _incidentService;

        #endregion

        #region 2. Constructors
        public VehicleIncidentManagementController(IVehicleManagementService vehicleManagementService
            , IBusinessUnitService businessUnitService
            , IIncidentService incidentService
            , IBusinessGroupService businessGroupService
            , ICenterService centerService
            , IVehicleDisposalService vehicleDisposalService           
            , IContactDetailService contactDetailService
            , IRegionService regionService
            , IModelService modelService
            , IVehicleTypeService vehicleTypeService
            , IAuditingService auditingService
            , UserManager<IdentityUser, Guid> userManager
            , IVehicleServiceService vehicleServiceService
            , IDepotTankService depotTankService
            , IAppRoleInterfaceAccessService appRoleInterfaceAccessService
            , IAppRoleMenuAccessService appRoleMenuAccessService
            , IAppRoleActionAccessService appRoleActionAccessService
            , IAppIssueService appIssueService
            , ISystemParameterService systemParameterService
            , ISystemParameterCodeService systemParameterCodeService

        ) : base(auditingService, userManager, contactDetailService, vehicleManagementService, vehicleServiceService
           , businessUnitService
           , businessGroupService
           , centerService
           , modelService
           , depotTankService
           , appRoleInterfaceAccessService
           , appRoleMenuAccessService
           , appRoleActionAccessService
            , systemParameterCodeService
            , systemParameterService
            , appIssueService
           )
        {
            _vehicleManagementService = vehicleManagementService;
            _businessUnitService = businessUnitService;
            _businessGroupService = businessGroupService;
            _centerService = centerService;
            _vehicleDisposalService = vehicleDisposalService;
            _systemParameterService = systemParameterService;
            _contactDetailService = contactDetailService;
            _regionService = regionService;
            _modelService = modelService;
            _vehicleTypeService = vehicleTypeService;
            _incidentService = incidentService;

        }
        #endregion

        #region 3. Actions

        #region 3.a. Get View Related Actions
        [HttpGet]
        public ActionResult VehicleIncidents(string message, bool isError)
        {
            ViewBag.NotificationMessage = message;
            ViewBag.NotificationIsError = isError;
            PopulateSelectListDataSources();

            return View();
        }
        [HttpGet]
        public ActionResult ViewVehicleIncidentDetails(int id)
        {

            var m = _incidentService.GetIncidentById(id);

            var v = Mapper.Map<Incident, IncidentDisplayViewModel>(m);

           return View("VehicleIncidentDetailsView", v);
        }
        [HttpGet]
        public ActionResult CreateVehicleIncidentDetails()
        {
            var v = new IncidentEditViewModel { Id = 0, DateAndTime = DateTime.Today };

            PopulateSelectListDataSources();

            return View("VehicleIncidentDetailsForm", v);

        }

        [HttpGet]
        public ActionResult EditVehicleIncidentDetails(int id)
        {
            var m = _incidentService.GetIncidentById(id);

            var v = Mapper.Map<Incident, IncidentEditViewModel>(m);

            PopulateSelectListDataSources();

            return View("VehicleIncidentDetailsForm", v);
        }

        #endregion

        #region 3.b. Get List of Values Related Actions

        #endregion

        #region 3.c. Grid Related Actions
        public ActionResult GetVehicleIncidentList([DataSourceRequest] DataSourceRequest request
            , int vehicleId, string incidentFileNumber, int incidentType)
        {

            var m = _incidentService.GetFilterByCenterPermission(CurrentUser
                            , vehicleId
                            , incidentFileNumber
                            , incidentType);

            var v = Mapper.Map<IEnumerable<Incident>, IEnumerable<IncidentDisplayViewModel>>(m);

            return Json(v.ToDataSourceResult(request));
        }



        #endregion

        #region 3.d. Form CRUD Post Related Actions

        [HttpPost]
        public ActionResult CheckIfVehicleIncidentIsInUse(int id)
        {
            try
            {
                if (ModelState.IsValid && id > 0)
                {

                    bool canDelete = _incidentService.CanDelete(id);

                    if (canDelete)
                    {
                        return Json(new { isInUse = false, message = "Vehicle Incident Is Not In Use.", isError = false });
                    }
                    else
                    {
                        return Json(new { isInUse = true, message = "Vehicle Incident Is In Use.", isError = false });
                    }
                }
                else
                {
                    return Json(new { isInUse = true, message = "The ModelState is invalid or the Id is 0.", isError = true });
                }
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    message = ex.Message.Length > 100 ? ex.Message.Substring(0, 100) + " ..." : ex.Message,
                    isError = true
                });
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateVehicleIncidentDetails(IncidentEditViewModel entityViewModel)
        {
            try
            {
                if (ModelState.IsValid && entityViewModel != null)
                {                   

                    var m = Mapper.Map<IncidentEditViewModel, Incident>(entityViewModel);

                    UpdateFiles();

                    m.CreatedBy = CurrentUser;
                    m.CreatedDate = DateTime.Now;

                    _incidentService.Create(m);

                    _incidentService.Save();

                    CreateAuditTrail(Parameters.DatabaseAction.Insert, Parameters.SubSystem.IncidentStatus, Parameters.Table.Incident);

                    return Json(new { message = "Changes saved successfully.", isError = false });
                }
                else
                {
                    return Json(new { message = "The ModelState is invalid or the ViewModel is null.", isError = true });
                }
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    message = ex.Message.Length > 100 ? ex.Message.Substring(0, 100) + " ..." : ex.Message,
                    isError = true
                });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateVehicleIncidentDetails(IncidentEditViewModel entityViewModel)
        {
            try
            {

                if (ModelState.IsValid && entityViewModel != null)
                {

                    var m = Mapper.Map<IncidentEditViewModel, Incident>(entityViewModel);

                    UpdateFiles();

                    m.LastUpdatedBy = CurrentUser;
                    m.LastUpdatedDate = DateTime.Now;

                    _incidentService.Update(m);

                    _incidentService.Save();

                    CreateAuditTrail(Parameters.DatabaseAction.Update, Parameters.SubSystem.IncidentStatus, Parameters.Table.Incident);

                    return Json(new { message = "Changes saved successfully.", isError = false });


                }
                else
                {
                    return Json(new { message = "The ModelState is invalid or the ViewModel is null.", isError = true });
                }
            }
            catch (Exception ex)
            {

                return Json(new
                {
                    message = ex.Message.Length > 100 ? ex.Message.Substring(0, 100) + " ..." : ex.Message,
                    isError = true
                });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteVehicleIncidentDetails(int id)
        {
            try
            {
                if (ModelState.IsValid && id != 0)
                {

                    var m = _incidentService.GetIncidentById(id);
                    _incidentService.Delete(m);
                    _incidentService.Save();

FMS.Web/Views/VehicleIncidentManagement/VehicleIncidentDetailsView.cshtml
@using FMS.Web.CustomHTMLHelpers
@using FMS.Common
@model FMS.Web.ViewModels.IncidentDisplayViewModel

@{
    ViewBag.Title = "Vehicle Incident Details";


    FileInfo incidentRptFileInfo = null;

    if (!string.IsNullOrEmpty(Model.IncidentFileName))
    {
        var fileNameIncidentRpt = Server.MapPath(Parameters.AppConstant.INCRPT_PATH + "/" + Model.IncidentFileName);

        if (System.IO.File.Exists(fileNameIncidentRpt))
        {
            incidentRptFileInfo = new System.IO.FileInfo(fileNameIncidentRpt);
        }
    }


}

<div class="container-fluid" style="margin-top:15px">
    <div class="row no-gutters h-100 justify-content-center align-items-center" style="background-color: azure; margin-top: 15px; margin-bottom: 15px;  padding: 5px;padding-left: 15px;">
        <div class="col-md-12">
            <div class="formHeadingRegion">
                <h4>@ViewBag.Title</h4>
            </div>
        </div>
    </div>
    <div class="row no-gutters h-100 justify-content-center align-items-center">
        <div class="col-md-10">

            <div class="container-fluid" id="FormContainer" style="margin-bottom:15px;">
                <div class="row no-gutters h-100 justify-content-center align-items-center">
                    <div class="col-md-6">
                        <div class="table-responsive">
                            <table class="table no-border">
                                <tr>
                                    <th> @Html.LabelFor(m => m.IncidentFileNumber)</th>
                                    <td>
                                        @Html.HiddenFor(m => m.Id)
                                        @Html.DisplayFor(m => m.IncidentFileNumber)

                                    </td>
                                </tr>
                                <tr>
                                    <th>@Html.LabelFor(m => m.IncidentStatus)</th>
                                    <td>
                                        @Html.DisplayFor(m => m.IncidentStatus)
                                    </td>
                                </tr>
                                <tr>
                                    <th>@Html.LabelForRequired(m => m.IncidentType)</th>
                                    <td>
                                        @Html.DisplayFor(m => m.IncidentType)
                                    </td>
                                </tr>
                                <tr>
                                    <th>@Html.LabelFor(m => m.IncidentDate)</th>
                                    <td>
                                        @Html.DisplayFor(m => m.IncidentDate)
                                    </td>
                                </tr>
                                <tr>
                                    <!--Vehicle dropdown list -->
                                    <th> @Html.LabelFor(m => m.RegistrationNumber)</th>
                                    <td>
                                        @Html.DisplayFor(m => m.RegistrationNumber)
                                    </td>
                                </tr>
                                <tr>
                                    <!--Driver dropdown list -->
                                    <th> @Html.LabelFor(m => m.Driver)</th>
                                    <td>
                                        @Html.DisplayFor(m => m.Driver)
                                    </td>
                                </tr>
                                <tr>
                                    <th>@Html.LabelFor(m => m.Location)</th>
                                    <td>
                                        @Html.DisplayFor(m => m.Location)
                                    </td>
                                </tr>

                                <tr>
                                    <th>@Html.LabelFor(m => m.Description)</th>
                                    <td colspan="2">
                                        @Html.DisplayFor(model => model.Description)
                                    </td>
                                </tr>

                            </table>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="table-responsive">
                            <table class="table no-border">

                                <tr>
                                    <th>@Html.LabelFor(m => m.IncidentRequiresService)</th>
                                    <td>
                                        @Html.DisplayFor(model => model.IncidentRequiresService)
                                    </td>
                                </tr>
                                <tr>
                                    <th>@Html.LabelFor(m => m.HasServiceBeenDone)</th>
                                    <td>
                                        @Html.DisplayFor(model => model.HasServiceBeenDone)
                                    </td>
                                </tr>
                                <tr>
                                    <th>@Html.LabelFor(m => m.HasReport)</th>
                                    <td>
                                        @Html.DisplayFor(model => model.HasReport)
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <fieldset id="fldsAccidentReportDetails">
                                            <legend style="font-size:14px !important">Accident Report Details</legend>
                                            <div class="table-responsive">
                                                <table class="table no-border">
                                                    <tr>
                                                        <th>@Html.LabelFor(model => model.IncidentFileName)</th>
                                                        <td>

                                                            @if (incidentRptFileInfo != null)
                                                            {
                                                                @(Html.Kendo().Button()
                                                                                                    .Name("btnDownloadReport")
                                                                                                    .Content("Download Report")
                                                                                                    .HtmlAttributes(new { type = "button", style = "margin-top:5px;" })
                                                                                                    .Events(ev => ev.Click("onDownloadClick"))
                                                                )
                                                            }


                                                        </td>


                                                    </tr>

                                                    <tr>
                                                        <th>@Html.LabelFor(m => m.DateofAccident)</th>
                                                        <td>
                                                            @Html.DisplayFor(m => m.DateofAccident)
                                                        </td>
                                                    </tr>

                                                </table>
                                            </div>
                                        </fieldset>
                                    </td>
                                </tr>
                                <tr>
                                    <th> @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "vwLabel" })</th>
                                    <td>
                                        <span>@Html.DisplayFor(model => model.CreatedBy)</span>
                                    </td>
                                </tr>

                                <tr>
                                    <th> @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "vwLabel" })</th>
                                    <td>
                                        <span>@Html.DisplayFor(model => model.CreatedDate)</span>
                                    </td>
                                </tr>

                                <tr>
                                    <th> @Html.LabelFor(model => model.LastUpdatedBy, htmlAttributes: new { @class = "vwLabel" })</th>
                                    <td>
                                        <span>@Html.DisplayFor(model => model.LastUpdatedBy)</span>
                                    </td>
                                </tr>

                                <tr>
                                    <th> @Html.LabelFor(model => model.LastUpdatedDate, htmlAttributes: new { @class = "vwLabel" })</th>
                                    <td>
                                        <span>@Html.DisplayFor(model => model.LastUpdatedDate)</span>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row no-gutters h-100 justify-content-center align-items-center">
                    <div class="col-md-12" style="margin-bottom: -10px;margin-top: -30px;">
                        <hr />
                    </div>
                </div>
                <div class="row no-gutters h-100 justify-content-center align-items-center" style="float: right;margin-right: 50px;">
                    <div class="col-md-12">
                        <div>

                            @(Html.Kendo().Button()
                                        .Name("btnBottomCancel")
                                        .Content("Back")
                                        .HtmlAttributes(new { type = "button", @class = "k-button" })
                                        .Icon("undo")
                            )
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <!--Vehicle Info-->
            @Html.DisplayFor(m => m.VehicleDisplayInfoViewModel, "VehicleInfoDisplay")
        </div>
    </div>
</div>
@section scripts{
    <script>




    $(document).ready(function () {
        $("#btnBottomCancel").click(function (event) {
            var newSrc = "NA";
            window.location.href = document.referrer.replace(/(message=).*?(&)/, '$1' + newSrc + '$2');
        });



    });



    function onDownloadClick(e) {
        e.preventDefault();
        @if (incidentRptFileInfo != null) {
            <text>
                window.location.href = '@Url.Action("DownloadFile", "VehicleIncidentManagement")?fileName=@incidentRptFileInfo.Name';
            </text>
        }
    }



    function onUpload(e) {
        $("#IncidentFileName").val(e.files[0].name);
        e.data = { fileType: "VehicleIncidentReport" };
    }

    function onRemove(e) {
        $("#IncidentFileName").val("");
        $("#btnDownloadReport").hide();
    }

    $("#VehicleId").change(function (e) {
        populateVehicleInfoBox(e.target.value);
    });

    $("#frmVehicleIncidentDetails").submit(function (event) {
        event.preventDefault();
        ajaxCreateUpdate(this, $("#Id").val(), "VehicleIncidentManagement", "CreateVehicleIncidentDetails", "UpdateVehicleIncidentDetails", "VehicleIncidents", "");
    });

    function toggleDisableAccidentReportFieldSet(isDisable) {
        if (isDisable) {
            $("#btnDownloadReport").prop("disabled", true);
            $("#files").data("kendoUpload").disable();
            $("#DateofAccident").data("kendoDatePicker").enable(false);
        }
        else {
            $("#btnDownloadReport").prop("disabled", false);
            $("#files").data("kendoUpload").enable();
            $("#DateofAccident").data("kendoDatePicker").enable(true);
        }
    }

    function checkToggleDisableAccidentReportFieldSet() {
        if ($("#HasReport").prop('checked')) {
            toggleDisableAccidentReportFieldSet(false);
        }
        else {
            toggleDisableAccidentReportFieldSet(true);
        }
    }



    </script>
    }