FMS.Web/Controllers/VehicleManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using FMS.Service;
using FMS.Web.ViewModels;
using FMS.Model;
using Kendo.Mvc.UI;
using AutoMapper;
using Kendo.Mvc.Extensions;
using System.Web;
using System.IO;
using FMS.Web.CustomActionFilters;
using FMS.Common;
using Microsoft.AspNet.Identity;
using FMS.Web.Identity;

namespace FMS.Web.Controllers
{
    [Authorize]
    [NoDirectAccess]
    public class VehicleManagementController : BaseController
    {
        #region 1. Private Members

        private readonly IVehicleManagementService _vehicleManagementService;
        private readonly IBusinessUnitService _businessUnitService;
        private readonly IBusinessGroupService _businessGroupService;
        private readonly ICenterService _centerService;
        private readonly IVehicleDisposalService _vehicleDisposalService;
        private readonly ISystemParameterService _systemParameterService;
        private readonly IContactDetailService _contactDetailService;
        private readonly IRegionService _regionService;
        private readonly IModelService _modelService;
        private readonly IVehicleTypeService _vehicleTypeService;
        private readonly IAppRoleActionAccessService _appRoleActionAccessService;


        #endregion

        #region 2. Constructors
        public VehicleManagementController(IVehicleManagementService vehicleManagementService
            , IBusinessUnitService businessUnitService
            , IBusinessGroupService businessGroupService
            , ICenterService centerService
            , IVehicleDisposalService vehicleDisposalService          
            , IContactDetailService contactDetailService
            , IRegionService regionService
            , IModelService modelService
            , IVehicleTypeService vehicleTypeService
            , IAuditingService auditingService
            , UserManager<IdentityUser, Guid> userManager
            , IVehicleServiceService vehicleServiceService
            , IDepotTankService depotTankService
            ,IAppRoleActionAccessService appRoleActionAccessService
            , IAppRoleInterfaceAccessService appRoleInterfaceAccessService
            , IAppRoleMenuAccessService appRoleMenuAccessService
            , IAppIssueService appIssueService
            , ISystemParameterService systemParameterService
            , ISystemParameterCodeService systemParameterCodeService

        ) : base(auditingService, userManager, contactDetailService, vehicleManagementService, vehicleServiceService
           , businessUnitService
           , businessGroupService
           , centerService
           , modelService
           , depotTankService
           , appRoleInterfaceAccessService
           , appRoleMenuAccessService
           , appRoleActionAccessService
            , systemParameterCodeService
            , systemParameterService
            , appIssueService
           )
        {
            _vehicleManagementService = vehicleManagementService;
            _businessUnitService = businessUnitService;
            _businessGroupService = businessGroupService;
            _centerService = centerService;
            _vehicleDisposalService = vehicleDisposalService;
            _systemParameterService = systemParameterService;
            _contactDetailService = contactDetailService;
            _regionService = regionService;
            _modelService = modelService;
            _vehicleTypeService = vehicleTypeService;
            _appRoleActionAccessService = appRoleActionAccessService;
         

        }
        #endregion

        #region 3. Actions

        #region 3.a. Get View Related Actions
       
        [HttpGet]
        [UserInterfaceAuthorization(Parameters.Interface.VEHICLE_REGISTER)]
        public ActionResult Vehicles(string message, bool isError)
        {
            ViewBag.NotificationMessage = message;
            ViewBag.NotificationIsError = isError;
            ViewBag.Centers = _centerService.GetAllCenterWithPermission(CurrentUser).Select(t => new { Value = t.CenterNumber, Text = t.Name });


            return View();
        }


        [HttpGet]
        [UserInterfaceAuthorization(Parameters.Interface.VIEW_BOS_VEHICLES)]
        public ActionResult VehiclesBOS()
        {
            ViewBag.Centers = _centerService.GetAllCenterWithPermission(CurrentUser).Select(t => new { Value = t.CenterNumber, Text = t.Name });
            return View();
        }



        [HttpGet]
        [UserActionAuthorization(Parameters.Action.VIEW_VEHICLES)]        
        public ActionResult GetVehicleDetails(int id)
        {

            var vm = this.PopulateVehicleViewDetails(id);
            return View("VehicleView", vm);
        }
        [HttpGet]
        [UserActionAuthorization(Parameters.Action.SETUP_NEW_VEHICLE)]
        public ActionResult CreateVehicle()
        {
            VehicleEditViewModel vehicleToCreate = new VehicleEditViewModel();
            this.PopulateSelectListDataSources();
            return View("VehicleForm", vehicleToCreate);
            
        }

        [HttpGet]
        [UserActionAuthorization(Parameters.Action.UPDATE_VEHICLE_REGISTRY)]
        public ActionResult EditVehicle(int id)
        {           
            var vehicleToEdit = _vehicleManagementService.GetVehicleById(id);            

            VehicleEditViewModel viewModelFormVehicle = Mapper.Map<Vehicle, VehicleEditViewModel>(vehicleToEdit);
          
            this.PopulateSelectListDataSources();

            return View("VehicleForm", viewModelFormVehicle);
        }

        #endregion

        #region 3.b. Get List of Values Related Actions

        #endregion

        #region 3.c. Grid Related Actions
        public ActionResult GetVehiclesList([DataSourceRequest] DataSourceRequest request
            , string assetNumber, string registrationNumber, int unitNumber, int groupNumber, int center)
        {

            var vehicles = _vehicleManagementService.GetFilterByCenterPermission(CurrentUser
                            , assetNumber
                            , registrationNumber
                            , unitNumber
                            , groupNumber
                            , center
                            );

            var viewModelVehicleList = Mapper.Map<IEnumerable<Vehicle>, IEnumerable<VehicleDisplayViewModel>>(vehicles);

            return Json(viewModelVehicleList.ToDataSourceResult(request));
        }

        public ActionResult GetBOSVehiclesList([DataSourceRequest] DataSourceRequest request
    , string assetNumber, string registrationNumber, int unitNumber, int groupNumber, int center)
        {

            var vehicles = _vehicleManagementService.GetFilterByCenterPermissionBOS(CurrentUser
                            , assetNumber
                            , registrationNumber
                            , unitNumber
                            , groupNumber
                            , center
                            );

            var viewModelVehicleList = Mapper.Map<IEnumerable<Vehicle>, IEnumerable<VehicleBOSDisplayViewModel>>(vehicles);

            return Json(viewModelVehicleList.ToDataSourceResult(request));
        }





        #endregion

        #region 3.d. Form CRUD Post Related Actions


        [HttpPost]
        public ActionResult CheckIfVehicleIsInUse(int id)
        {
            try
            {
                if (ModelState.IsValid && id != 0)
                {

                    bool isInUse = _vehicleManagementService.IsInUse(id);

                    if (isInUse)
                    {
                        return Json(new { isInUse = true, message = "Vehicle Is In Use.", isError = false });
                    }
                    else
                    {
                        return Json(new { isInUse = false, message = "Vehicle Is Not In Use.", isError = false });
                    }
                }
                else
                {
                    return Json(new { isInUse = true, message = "The ModelState is invalid or the Id is 0.", isError = true });
                }
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    message = ex.Message.Length > 100 ? ex.Message.Substring(0, 100) + " ..." : ex.Message,
                    isError = true
                });
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserActionAuthorization(Parameters.Action.SETUP_NEW_VEHICLE)]
        public ActionResult CreateVehicle(VehicleEditViewModel entityViewModel)
        {
            try
            {
                if (ModelState.IsValid && entityViewModel != null)
                {

                        var vehicle = Mapper.Map<VehicleEditViewModel, Vehicle>(entityViewModel);

                        UpdateFiles();

                        vehicle.CreatedBy = CurrentUser;
                        vehicle.CreatedDate = DateTime.Now;


                        _vehicleManagementService.Create(vehicle);               

                        _vehicleManagementService.Save();

                        CreateAuditTrail(Parameters.DatabaseAction.Insert,Parameters.SubSystem.Vehicle,Parameters.Table.Vehicle);

                        return Json(new { message = "Changes saved successfully.", isError = false });

                }
                else
                {
                    return Json(new { message = "The ModelState is invalid or the ViewModel is null.", isError = true });
                }
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    message = ex.Message.Length > 100 ? ex.Message.Substring(0, 100) + " ..." : ex.Message,
                    isError = true
                });
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]

FMS.Web/Views/VehicleManagement/VehicleView.cshtml
@using FMS.Common

@model FMS.Web.ViewModels.VehicleDisplayViewModel

@{
    ViewBag.Title = "Vehicle Information";

    FileInfo codRptFileInfo = null, bosRptFileInfo = null;

    if (!string.IsNullOrEmpty(Model.BosReport))
    {
        var fileNameBOSRpt = Server.MapPath(Parameters.AppConstant.BOSRPT_PATH + "/" + Model.BosReport);

        if (System.IO.File.Exists(fileNameBOSRpt))
        {
            bosRptFileInfo = new System.IO.FileInfo(fileNameBOSRpt);
        }
    }


    if (!string.IsNullOrEmpty(Model.CODReport))
    {
        var fileNameCODRpt = Server.MapPath(Parameters.AppConstant.CODRPT_PATH + "/" + Model.CODReport);

        if (System.IO.File.Exists(fileNameCODRpt))
        {
            codRptFileInfo = new System.IO.FileInfo(fileNameCODRpt);
        }
    }



}
<div class="container-fluid" id="view-details">
    <div class="row no-gutters h-100 justify-content-center align-items-center" style="background-color: azure; margin-top: 15px; margin-bottom: 15px;  padding: 5px;padding-left: 15px;">
        <div class="col-md-6">
            <div class="formHeadingRegion">
                <h4>@ViewBag.Title</h4>
            </div>
        </div>
        <div class="col-md-6">
            <div class="formButtonRegion">
                @(Html.Kendo().Button()
                    .Name("btnBack")
                    .Content("Back")
                    .HtmlAttributes(new { type = "button", @class = "k-button", style = "float:right;margin:10px;" })
                    .Icon("undo")
                )
            </div>
        </div>
    </div>
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-md-12">
            <div class="k-content">
                @(Html.Kendo().TabStrip()
                                                            .Name("tbsVehicle")
                                                            .HtmlAttributes(new { style = "clear:both" })
                                                            .Animation(animation =>
                                                                animation.Open(effect =>
                                                                    effect.Fade(FadeDirection.In)))
                                                            .Items(tabstrip =>
                                                            {
                                                                tabstrip.Add().Text("Asset Information")
                                                                    .Selected(true)
                                                                    .Content(@<text>
                                                                        @Html.Partial("~/Views/VehicleManagement/Partial/_VehicleAssetInformationViewPartial.cshtml", Model, new ViewDataDictionary { { "bosRptFileInfo", bosRptFileInfo } })
                                                                    </text>);
                                                                tabstrip.Add().Text("Vehicle Expiry Date")
                                                                    .Content(vm => Html.Partial("~/Views/VehicleManagement/Partial/_VehicleExpiryDateViewPartial.cshtml", vm));

                                                                tabstrip.Add().Text("Vehicle Current Status")
                                                                    .Content(vm => Html.Partial("~/Views/VehicleManagement/Partial/_VehicleCurrentStatusViewPartial.cshtml", vm));

                                                                tabstrip.Add().Text("Disposal Information")
                                                                    .Content(@<text>
                                                                        @Html.Partial("~/Views/VehicleManagement/Partial/_VehicleDisposalViewPartial.cshtml", Model, new ViewDataDictionary { { "codRptFileInfo", codRptFileInfo } })
                                                                    </text>);

                                                                tabstrip.Add().Text("Audit Details")
                                                                    .Content(vm => Html.Partial("~/Views/VehicleManagement/Partial/_VehicleAuditViewPartial.cshtml", vm));
                                                            })
                )
            </div>
        </div>
    </div>
</div>
<style>
    #tbsVehicle > .k-content {
        overflow: visible;
    }
</style>
@section scripts{
    <script type="text/javascript">


    function error_handler(e) {
        if (e.errors) {
            var message = "Errors:\n";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });
            alert(message);
        }
    }

    function onBOSRptDownloadClick(e) {
        e.preventDefault();

        @if (bosRptFileInfo != null) {
            <text>
                window.location.href = '@Url.Action("DownloadFile", "VehicleManagement")?fileName=@bosRptFileInfo.Name';
            </text>
        }
    }


    function onCODRptDownloadClick(e) {
        e.preventDefault();

        @if (codRptFileInfo != null) {
            <text>
                window.location.href = '@Url.Action("DownloadFile", "VehicleDisposal")?fileName=@codRptFileInfo.Name';
            </text>
        }
    }




    $(document).ready(function () {



        $("#btnBack").click(function (event) {
            var newSrc = "NA";
            window.location.href = document.referrer.replace(/(message=).*?(&)/, '$1' + newSrc + '$2');
        });

    });

    </script>
    }